services:
  backend:
    build:
      context: ./backend
    container_name: plmetrix-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    container_name: plmetrix-frontend
    ports:
      - "5006:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always
